### ISSUE TITLE
Move here the repository settings file

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#7]
**Context**

With this issue you create 2 pull requests.

`.github` repositories are a place for storing community health files for the whole organization, so you do not duplicate `CONTRIBUTION` guides and others. We choose it as a place for other general files too, like for example https://github.com/asyncapi/.github/blob/master/recognize-contributors.md.

**Description**

This is what needs to be done:
- Remove [this](https://github.com/asyncapi/asyncapi/blob/master/documents/git-workflow.md) file as it is already [here](https://github.com/asyncapi/.github/blob/master/git-workflow.md)
- Remove [this](https://github.com/asyncapi/asyncapi/blob/master/documents/repository-settings.md) file and create it [here](https://github.com/asyncapi/.github/) in the root of the repository. Add to the newly created document information about:
  - Additional workflows that need to be created in each repository:
    - Release workflow that should be based on [this](https://github.com/asyncapi/html-template/blob/master/.github/workflows/release.yml) workflow (including tweeting) 
    - Automerge workflow that should be based on [this](https://github.com/asyncapi/html-template/blob/master/.github/workflows/automerge-release-pr-bump.yml). Adjust `if` statements to check `github.actor == 'asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'` instead of `github.actor == 'asyncapi-bot'`
  - Add this workflow file called `sentiment-analysis.yml` as somethign that every repo must have:
    ```yaml
    name: 'Sentiment Analysis'

    on: 
    issue_comment:
        types: 
        - created
        - edited
    issues:
        types:
        - opened
        - edited
    pull_request:
        types:
        - opened
        - edited
    pull_request_review:
        types:
        - submitted
        - edited
    pull_request_review_comment:
        types:
        - created
        - edited
    jobs:
    test:
        name: Checking sentiments
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Check sentiment
            uses: derberg/code-of-conduct-sentiment-analysis-github-action@v1
            id: sentiments
            with:
            gcp_key: ${{ secrets.GCP_KEY_SENTIMENT }} 
        - uses: someimportantcompany/github-actions-slack-message@v1
            # this step runs only if sentiment is a negative numner
            if: steps.sentiments.outputs.sentiment < 0
            with:
            webhook-url: ${{ secrets.SLACK_SENTIMENTS }}
            text: Here ${{steps.sentiments.outputs.source}} you can find a potential negative text that requires your attention as the sentiment analysis score is ${{steps.sentiments.outputs.sentiment}}
            color: orange
    ```
  - Each repository must be integrated with https://sonarcloud.io/organizations/asyncapi/projects for automated quality and security scans﻿
