### ISSUE TITLE
autoupdate is not working as planned 😅 

### ISSUE THREAD

**Issue by derberg** [asyncapi/.github#99]
Action `pullreminders/label-when-approved-action@v1.0.7` work only with event `pull_request_review` but when `hmarr/auto-approve-action@v2` performs approval, the review event is not triggered because in general this is how GH Workflows work, the operations that are performed by them do not trigger events.

So we will never label the PR and therefore we will never autoupdate as we planned here https://github.com/asyncapi/.github/pull/85

There is no other alternative than I think:
- removing this job https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge.yml#L49
- replace it with custom GraphQL calls or, because it is needed only for autoupdates, we can just use there a simple action just to add a label without checking if PR is approved or not as in the end it doesn't matter. We would only have to make sure it also runs once `if: github.actor == ('asyncapi-bot' || github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]') && !contains(github.event.pull_request.labels.*.name, 'released')` condition is met:
   ```yml
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['autoapprove']
            }) 
   ```

other ideas?
